const { spawn } = require("child_process");

/**
 * =========================================================
 * KryomCode Test Runner
 * =========================================================
 *
 * Responsible for:
 * - Starting pytest
 * - Streaming stdout/stderr
 * - Tracking the active test process
 * - Stopping the test process
 * - Preventing duplicate test runs
 *
 * This service does NOT:
 * - Manage Electron windows
 * - Manage IPC
 * - Manage project selection
 * - Manage the integrated terminal
 *
 * Those responsibilities remain in main.cjs.
 * =========================================================
 */

let testProcess = null;
let testProjectPath = null;

/**
 * Normalize an optional value into a safe string.
 */
function normalizeProjectPath(projectPath) {
  if (
    typeof projectPath !== "string" ||
    projectPath.trim() === ""
  ) {
    throw new Error(
      "A valid project path is required.",
    );
  }

  return projectPath;
}

/**
 * Check whether tests are currently running.
 */
function isRunning() {
  return testProcess !== null;
}

/**
 * Return the project associated with
 * the currently running test process.
 */
function getProjectPath() {
  return testProjectPath;
}

/**
 * Start pytest in the supplied project.
 *
 * The caller is responsible for validating
 * that the project path belongs to the
 * currently opened project.
 *
 * @param {object} options
 * @param {string} options.projectPath
 * @param {(data: string) => void} [options.onOutput]
 * @param {(data: string) => void} [options.onError]
 * @param {(code: number|null) => void} [options.onExit]
 * @param {(error: Error) => void} [options.onProcessError]
 *
 * @returns {{
 *   success: boolean,
 *   alreadyRunning?: boolean
 * }}
 */
function startTests({
  projectPath,
  onOutput,
  onError,
  onExit,
  onProcessError,
}) {
  const safeProjectPath =
    normalizeProjectPath(projectPath);

  /**
   * Do not allow two pytest processes
   * to run at the same time.
   */
  if (testProcess) {
    return {
      success: true,
      alreadyRunning: true,
    };
  }

  testProjectPath = safeProjectPath;

  /**
   * Windows uses the pytest executable
   * generated by the active Python
   * environment.
   *
   * `python -m pytest` is preferred because
   * it works better with virtual environments
   * and avoids depending on PATH resolving
   * a standalone pytest executable.
   */
  const command =
    process.platform === "win32"
      ? "python"
      : "python3";

  const args = [
    "-m",
    "pytest",
  ];

  testProcess = spawn(
    command,
    args,
    {
      cwd: safeProjectPath,

      windowsHide: true,

      stdio: [
        "ignore",
        "pipe",
        "pipe",
      ],

      shell: false,
    },
  );

  /**
   * Capture stdout.
   */
  testProcess.stdout.on(
    "data",
    (data) => {
      if (typeof onOutput === "function") {
        onOutput(data.toString());
      }
    },
  );

  /**
   * Capture stderr.
   */
  testProcess.stderr.on(
    "data",
    (data) => {
      if (typeof onError === "function") {
        onError(data.toString());
      }
    },
  );

  /**
   * Process-level error.
   *
   * Example:
   * - Python is not installed
   * - process could not be spawned
   */
  testProcess.on(
    "error",
    (error) => {
      if (
        typeof onProcessError ===
        "function"
      ) {
        onProcessError(error);
      }

      testProcess = null;
      testProjectPath = null;
    },
  );

  /**
   * Process exit.
   */
  testProcess.on(
    "close",
    (code) => {
      if (
        typeof onExit === "function"
      ) {
        onExit(code);
      }

      testProcess = null;
      testProjectPath = null;
    },
  );

  return {
    success: true,
    alreadyRunning: false,
  };
}

/**
 * Stop the currently running test process.
 *
 * Returns false when there is no active
 * test process.
 */
function stopTests() {
  if (!testProcess) {
    testProjectPath = null;

    return {
      success: true,
      wasRunning: false,
    };
  }

  try {
    testProcess.kill();
  } catch (error) {
    console.error(
      "Failed to stop test process:",
      error,
    );
  }

  /**
   * Do not immediately clear testProcess
   * here. The `close` event will perform
   * final cleanup.
   */
  return {
    success: true,
    wasRunning: true,
  };
}

/**
 * Stop tests only when they belong to
 * the supplied project.
 *
 * Useful when the user switches projects.
 */
function stopTestsForProject(
  projectPath,
) {
  if (
    !testProcess ||
    testProjectPath !== projectPath
  ) {
    return {
      success: true,
      wasRunning: false,
    };
  }

  return stopTests();
}

/**
 * Clean up the test process.
 *
 * This is intended for Electron
 * application shutdown.
 */
function cleanup() {
  if (!testProcess) {
    testProjectPath = null;
    return;
  }

  try {
    testProcess.kill();
  } catch (error) {
    console.error(
      "Failed to clean up test process:",
      error,
    );
  }

  testProcess = null;
  testProjectPath = null;
}

module.exports = {
  startTests,
  stopTests,
  stopTestsForProject,
  isRunning,
  getProjectPath,
  cleanup,
};